# Generated by Django 5.0.9 on 2026-07-23 03:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('image', models.URLField(blank=True)),
                ('card_image', models.URLField(blank=True, help_text='Illustration de la carte de collection')),
                ('biography', models.TextField()),
                ('quote', models.CharField(blank=True, max_length=280)),
                ('unlock_level', models.PositiveIntegerField(default=1, help_text="Niveau de joueur minimum requis (independamment d'un chapitre precis)")),
                ('rarity', models.CharField(choices=[('common', 'Commun'), ('rare', 'Rare'), ('epic', 'Epique'), ('legendary', 'Legendaire')], default='common', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heroes', to='geography.department')),
            ],
            options={
                'verbose_name': 'Heros',
                'verbose_name_plural': 'Heros',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeroCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='heroes.hero')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_cards', to='accounts.userprofile')),
                ('unlocked_via_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geography.level')),
            ],
            options={
                'verbose_name': 'Carte de heros',
                'verbose_name_plural': 'Cartes de heros',
                'ordering': ['-unlocked_at'],
                'unique_together': {('profile', 'hero')},
            },
        ),
    ]
