# Generated by Django 5.0.9 on 2026-07-23 03:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveSmallIntegerField(default=1, help_text='1 pour un duel ou une battle entre amis')),
                ('question_count', models.PositiveSmallIntegerField(default=10)),
                ('time_limit_seconds', models.PositiveSmallIntegerField(default=30, help_text='Par question')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('ongoing', 'En cours'), ('finished', 'Termine'), ('cancelled', 'Annule')], default='pending', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participant au match',
                'verbose_name_plural': 'Participants aux matchs',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='BattleRoom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(help_text="Code d'invitation (battle entre amis)", max_length=8, unique=True)),
                ('room_type', models.CharField(choices=[('duel', 'Duel 1v1'), ('friend', 'Battle entre amis'), ('tournament', 'Tournoi')], default='duel', max_length=12)),
                ('max_players', models.PositiveSmallIntegerField(default=2, help_text='2 (duel/amis) ou 8/16/32 (tournoi)')),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('in_progress', 'En cours'), ('finished', 'Termine'), ('cancelled', 'Annule')], default='waiting', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to='accounts.userprofile')),
                ('rematch_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematches', to='battles.battleroom')),
            ],
            options={
                'verbose_name': 'Salle de battle',
                'verbose_name_plural': 'Salles de battle',
            },
        ),
    ]
