# Generated by Django 5.2.16 on 2026-07-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('battles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleroom',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Joueurs ayant rejoint la salle (hote inclus)', related_name='joined_rooms', to='accounts.userprofile'),
        ),
    ]
