# Generated by Django 5.0.9 on 2026-07-23 03:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('friend_request', "Demande d'ami"), ('challenge', 'Defi'), ('achievement', 'Achievement debloque'), ('season', 'Saison'), ('reward', 'Recompense'), ('system', 'Systeme')], max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('message', models.TextField(blank=True)),
                ('action_url', models.CharField(blank=True, help_text='Route frontend a ouvrir, ex: /amis', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
