# Generated by Django 5.2.16 on 2026-07-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprogress',
            name='pending_stake',
            field=models.PositiveIntegerField(default=0, help_text='Pieces misees sur le chapitre courant, en attente du resultat'),
        ),
    ]
