# Generated by Django 5.0.9 on 2026-07-23 03:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('code', models.CharField(help_text='Ex: OU, ND, NE, NO, ART, CTR, SUD, SE, GA, NIP', max_length=6, unique=True)),
                ('capital', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('map_image', models.URLField(blank=True, help_text='Image/illustration sur la carte interactive')),
                ('icon', models.URLField(blank=True)),
                ('boss_name', models.CharField(blank=True, help_text='Nom du boss final du departement', max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'apparition sur la carte")),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('question_count', models.PositiveSmallIntegerField(default=10)),
                ('required_score', models.PositiveSmallIntegerField(default=70, help_text='Pourcentage minimum de bonnes reponses pour valider le chapitre')),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('coin_reward', models.PositiveIntegerField(default=20)),
                ('is_boss_level', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='geography.department')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['department__order', 'order'],
            },
        ),
    ]
