# Generated by Django 5.0.9 on 2026-07-23 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='unlocks_hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_by_levels', to='heroes.hero'),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('department', 'order')},
        ),
    ]
