# Generated by Django 5.2.16 on 2026-07-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='stake_cost',
            field=models.PositiveIntegerField(default=25, help_text="Pieces a miser pour tenter ce chapitre (perdues en cas d'echec)"),
        ),
    ]
