# Generated by Django 5.0.9 on 2026-07-23 03:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('mission_type', models.CharField(choices=[('answer_questions', 'Repondre a des questions'), ('win_matches', 'Gagner des matchs'), ('correct_streak', 'Serie de bonnes reponses'), ('play_department', 'Jouer dans un departement')], max_length=20)),
                ('target_value', models.PositiveIntegerField(help_text="Ex: 20 pour 'Repondre a 20 questions'")),
                ('xp_reward', models.PositiveIntegerField(default=20)),
                ('coin_reward', models.PositiveIntegerField(default=10)),
                ('is_daily', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('avatar', 'Avatar'), ('frame', 'Cadre de profil'), ('booster', 'Booster')], max_length=10)),
                ('image', models.URLField(blank=True)),
                ('price_coins', models.PositiveIntegerField(default=0)),
                ('price_diamonds', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article boutique',
                'verbose_name_plural': 'Articles boutique',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('reward_type', models.CharField(choices=[('coins', 'Pieces'), ('diamonds', 'Diamants'), ('badge', 'Badge'), ('avatar', 'Avatar'), ('frame', 'Cadre de profil'), ('hero', 'Heros'), ('chest_bronze', 'Coffre bronze'), ('chest_silver', 'Coffre argent'), ('chest_gold', 'Coffre or')], max_length=20)),
                ('image', models.URLField(blank=True)),
                ('coins_amount', models.PositiveIntegerField(default=0)),
                ('diamonds_amount', models.PositiveIntegerField(default=0)),
                ('xp_amount', models.PositiveIntegerField(default=0)),
                ('grants_hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_by_rewards', to='heroes.hero')),
            ],
            options={
                'verbose_name': 'Recompense',
                'verbose_name_plural': 'Recompenses',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.URLField(blank=True)),
                ('criteria_type', models.CharField(choices=[('questions_answered', 'Questions repondues'), ('matches_won', 'Matchs gagnes'), ('win_streak', 'Serie de victoires'), ('departments_completed', 'Departements termines'), ('heroes_collected', 'Heros collectionnes')], max_length=30)),
                ('criteria_value', models.PositiveIntegerField()),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='rewards.reward')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_paid_coins', models.PositiveIntegerField(default=0)),
                ('price_paid_diamonds', models.PositiveIntegerField(default=0)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.userprofile')),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='rewards.shopitem')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='rewards.achievement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Achievement du joueur',
                'verbose_name_plural': 'Achievements des joueurs',
                'unique_together': {('profile', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rewards.mission')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Mission du joueur',
                'verbose_name_plural': 'Missions des joueurs',
                'unique_together': {('profile', 'mission', 'assigned_date')},
            },
        ),
    ]
