# Generated by Django 5.2.16 on 2026-07-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermission',
            name='reward_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
