# Generated by Django 5.2.16 on 2026-07-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ad_rewards_claimed_today",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ad_rewards_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
