# Generated by Django 5.2.16 on 2026-07-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_ad_rewards_claimed_today_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="ad_rewards_claimed_today",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="ad_rewards_date",
        ),
    ]
