# Generated by Django 5.2.16 on 2026-07-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_ad_rewards_claimed_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Derniere requete authentifiee (presence en ligne)', null=True),
        ),
    ]
