# Generated by Django 5.2.16 on 2026-07-24 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_remove_userprofile_ad_rewards_claimed_today_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiamondPack",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("diamonds_amount", models.PositiveIntegerField()),
                (
                    "price_usd_cents",
                    models.PositiveIntegerField(
                        help_text="Prix en cents USD (ex: 299 pour 2,99 $)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Pack de diamants",
                "verbose_name_plural": "Packs de diamants",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DiamondPurchase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("paypal", "PayPal")],
                        max_length=20,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        help_text="ID de session/commande cote fournisseur",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("paid", "Paye"),
                            ("failed", "Echoue"),
                            ("cancelled", "Annule"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("diamonds_credited", models.BooleanField(default=False)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="payments.diamondpack",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diamond_purchases",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achat de diamants",
                "verbose_name_plural": "Achats de diamants",
            },
        ),
    ]
