# Generated by Django 5.0.9 on 2026-07-23 03:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.URLField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Evenement',
                'verbose_name_plural': 'Evenements',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('national', 'National'), ('department', 'Departement'), ('friends', 'Amis')], default='national', max_length=12)),
                ('period', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('yearly', 'Annuel'), ('season', 'Saison'), ('all_time', 'Historique')], default='weekly', max_length=10)),
                ('score', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classement',
                'verbose_name_plural': 'Classements',
                'ordering': ['scope', 'period', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('theme', models.CharField(blank=True, help_text="Ex: Saison des heros de l'independance", max_length=160)),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.URLField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Saison',
                'verbose_name_plural': 'Saisons',
                'ordering': ['-start_date'],
            },
        ),
    ]
