# Generated by Django 5.0.9 on 2026-07-23 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('competition', '0001_initial'),
        ('geography', '0001_initial'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='rewards.reward'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='geography.department'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='competition.season'),
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='competition.season'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together={('scope', 'period', 'department', 'season', 'profile', 'period_start')},
        ),
    ]
